Repository kendallm360/fitLitty, pull requests merged in 2022-06, with the labels that each got.

#56 Feature/build activity dashboard
  dist/index.html
  src/activityRepository.js
  src/graphs.js
  src/scripts.js
Labels: Implement

#58 Feature/activity widgets
  src/graphs.js
  src/scripts.js
Labels: enhancement

#60 Feature/add more activity tests
  src/activityRepository.js
  test/ActivityRepository-test.js
Labels: enhancement

#70 Refactor/refactor to show activity widgets on click
  dist/index.html
  src/css/styles.css
  src/graphs.js
  src/scripts.js
Labels: refactor

#72 Fix postData so that the Promise must be resolved before fetching updated data from API
  src/apiCalls.js
  src/scripts.js
Labels: bug
